### ISSUE TITLE
Ordering by event time

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/ChoralStorm#16]
Currently there is no way to run a query and order the results by their event time.

**Comment by james-woo** [comment]
If you run SELECT * FROM choraldatastream.raw_data where device_id=SOME_DEVICE_ID; The results returned are ordered by their event time. What is the issue?

**Comment by andreirtaylor** [comment]
They are ordered in descending order. What if you want ascending?

**Comment by james-woo** [comment]
SELECT * FROM choraldatastream.raw_data WHERE device_id=SOME_DEVICE_ID ORDER BY device_timestamp [ASC|DESC]

**Comment by andreirtaylor** [comment]
I was trying to sort by received time. If you can sort by the time the request was sent that should be enough.
