### ISSUE TITLE
Kafka Connection Issues

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/ChoralStorm#5]
This is a low priority item but it would be nice to know if kafka is able to actually complete the request. The issues that I was having were due to kafka successfully receiving the message but storm not being able to process them.

**Comment by james-woo** [comment]
If you use localhost:8080, you can view any errors happening with any of the bolts
1. Click on ChoralTopology
2. View bolts and errors will appear under Error Host (shows stack trace)
