### ISSUE TITLE
Event posts do not get saved

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/ChoralStorm#7]
Run Choral Storm and use the device mock from Choral Allegro
Run with a high number of mocked devices (I used 2000) after a while the requests stop getting processed
If you manually remove the events from cassandra then the database gets populated with the old messages (use cassandras TRUNCATE to clear events)

**Comment by james-woo** [comment]
It is probably related to these lines of code:

https://github.com/ChoralCloud/ChoralStorm/blob/master/src/main/java/storm/ChoralTopology.java#L34-L38

Perhaps the startOffsetTime is not actually working? I will investigate further.

**Comment by andreirtaylor** [comment]
I ran it overnight and got up to 137,000 rows in cassandra.
And james and I were talking and we think its a volume issue. Something in choral storm buckles under a heavy load.

**Comment by james-woo** [comment]
Removing average queries seems to have fixed this issue.
